# Generated by Django 5.0.6 on 2026-08-18 23:14

import validadores
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('autenticacao', '0002_alter_usuario_creditos_alter_usuario_telefone'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuario',
            name='cpf',
            field=models.CharField(max_length=16, unique=True, validators=[validadores.validar_cpf]),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='telefone',
            field=models.CharField(max_length=20, validators=[validadores.validar_telefone]),
        ),
    ]
