# Generated by Django 5.0.6 on 2026-08-19 23:20

import django.core.validators
import django.db.models.deletion
import django.db.models.functions.text
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_corrige_inversao_p_k'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Calcario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(help_text='Ex: Calcário dolomítico - Fornecedor X', max_length=255)),
                ('tipo', models.CharField(choices=[('calcitico', 'Calcítico (MgO abaixo de 5%)'), ('magnesiano', 'Magnesiano (MgO entre 5% e 12%)'), ('dolomitico', 'Dolomítico (MgO acima de 12%)')], max_length=20)),
                ('prnt', models.DecimalField(decimal_places=2, max_digits=5, validators=[django.core.validators.MinValueValidator(Decimal('1')), django.core.validators.MaxValueValidator(Decimal('150'))], verbose_name='PRNT (%)')),
                ('teor_cao', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, validators=[django.core.validators.MinValueValidator(Decimal('0')), django.core.validators.MaxValueValidator(Decimal('100'))], verbose_name='Teor de CaO (%)')),
                ('teor_mgo', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, validators=[django.core.validators.MinValueValidator(Decimal('0')), django.core.validators.MaxValueValidator(Decimal('100'))], verbose_name='Teor de MgO (%)')),
            ],
            options={
                'verbose_name': 'Calcário',
                'verbose_name_plural': 'Calcários',
                'ordering': ['nome'],
            },
        ),
        migrations.AddField(
            model_name='cultura',
            name='saturacao_bases_desejada',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, validators=[django.core.validators.MinValueValidator(Decimal('0')), django.core.validators.MaxValueValidator(Decimal('100'))], verbose_name='Saturação por bases desejada (V₂) em %'),
        ),
        migrations.AddConstraint(
            model_name='cultura',
            constraint=models.UniqueConstraint(django.db.models.functions.text.Lower('nome'), models.F('usuario'), name='cultura_unica_por_usuario'),
        ),
        migrations.AddField(
            model_name='calcario',
            name='usuario',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddConstraint(
            model_name='calcario',
            constraint=models.UniqueConstraint(django.db.models.functions.text.Lower('nome'), models.F('usuario'), name='calcario_unico_por_usuario'),
        ),
    ]
