# Generated by Django 5.0.6 on 2026-08-19 23:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_calcario_cultura_saturacao_bases_desejada_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='analisesolo',
            name='camada',
            field=models.CharField(choices=[('0-20', '0 a 20 cm (superficial)'), ('20-40', '20 a 40 cm (subsuperficial)'), ('40-60', '40 a 60 cm'), ('outra', 'Outra')], default='0-20', max_length=10, verbose_name='Camada amostrada'),
        ),
    ]
