# Generated by Django 5.0.6 on 2026-08-20 00:35

import django.core.validators
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_analisesolo_camada'),
    ]

    operations = [
        migrations.AddField(
            model_name='cultura',
            name='enxofre_desejado',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True, validators=[django.core.validators.MinValueValidator(Decimal('0'))], verbose_name='Enxofre desejado (mg/dm³)'),
        ),
        migrations.AddField(
            model_name='cultura',
            name='fator_fixacao_fosforo',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True, validators=[django.core.validators.MinValueValidator(Decimal('0'))], verbose_name='kg de P₂O₅ por mg/dm³ de P a elevar'),
        ),
        migrations.AddField(
            model_name='cultura',
            name='fosforo_desejado',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True, validators=[django.core.validators.MinValueValidator(Decimal('0'))], verbose_name='Fósforo desejado (mg/dm³)'),
        ),
        migrations.AddField(
            model_name='cultura',
            name='nitrogenio_recomendado',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=7, null=True, validators=[django.core.validators.MinValueValidator(Decimal('0'))], verbose_name='Nitrogênio recomendado (kg/ha)'),
        ),
        migrations.AddField(
            model_name='cultura',
            name='saturacao_k_desejada',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, validators=[django.core.validators.MinValueValidator(Decimal('0')), django.core.validators.MaxValueValidator(Decimal('100'))], verbose_name='Saturação de K na CTC desejada (%)'),
        ),
    ]
