# Generated by Django 5.0.6 on 2026-08-20 23:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_cultura_enxofre_desejado_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='analisesolo',
            name='cultura',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='core.cultura'),
        ),
        migrations.AlterField(
            model_name='analisesolo',
            name='laboratorio',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='core.laboratorio'),
        ),
    ]
